name: Cross-Platform Release

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CRATE_NAME: images-optimizer

jobs:
  build-and-release:
    name: Build - ${{ matrix.os_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os_name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_name: images-optimizer
            asset_name: images-optimizer-linux
          
          - os_name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin_name: images-optimizer.exe
            asset_name: images-optimizer-windows.exe
          
          - os_name: macOS
            os: macos-latest
            target: x86_64-apple-darwin
            bin_name: images-optimizer
            asset_name: images-optimizer-macos

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm pkg-config libssl-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install nasm

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: choco install nasm

    - name: Prepare Windows Binaries
      if: runner.os == 'Windows'
      shell: bash
      run: |
        mkdir -p bin
        curl -L -o pngquant.zip https://pngquant.org/pngquant-windows.zip 
        unzip -j -o pngquant.zip "*/pngquant.exe" -d bin
        curl -L -o oxipng.zip https://github.com/shssoichiro/oxipng/releases/download/v9.0.0/oxipng-9.0.0-x86_64-pc-windows-msvc.zip
        unzip -j -o oxipng.zip "*/oxipng.exe" -d bin

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Rust Cache
      uses: swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    - name: Build Binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Rename and Move Binary
      shell: bash
      run: |
        cp target/${{ matrix.target }}/release/${{ matrix.bin_name }} ${{ matrix.asset_name }}

    - name: Upload to Nightly Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: nightly
        name: Nightly Build
        prerelease: true
        files: ${{ matrix.asset_name }}
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
